name: Upload Python Package to PyPI when a Release is Created

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - created
  release:
    types: [published]

jobs:
  pypi-publish:
    name: Publish release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/abdel-langchain
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: pdm-project/setup-pdm@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build dependencies
        run: pdm  build

      - name: Log secret (wrong)
        run: |
          echo "PYPI_API_TOKEN is: ${{ secrets.PYPI_API_TOKEN }}"

      - name: Publish package distributions to PyPI
        # run: pdm publish
        uses: pypa/gh-action-pypi-publish@v1.12.3
        with:
          username: ${{ secrets.PYPI_USERNAME }}
          password: ${{ secrets.PYPI_API_TOKEN }}

      # - name: Run tests
      #   run: pdm run pytest
